Updated README.md
KapilKumar7/Hacktoberfest2022-masai pull request #46
Opened 2022-10-16 15:37 UTC by Nikita0509

2022-10-16 15:38 UTC, KapilKumar7 requested changes
Please add your name Alphabetically.

2022-10-16 16:32 UTC, Nikita0509 commented
I added my name under N alphabet so its in correct order, then what is the issue ??

2022-10-17 02:12 UTC, KapilKumar7 commented
> I added my name under N alphabet so its in correct order, then what is the issue ??

Your name must come before Nishant in alphabetical order . Thanks for your valuable contribution 😊. Don't forget to ✨ our Repository.

2022-10-17 02:13 UTC, KapilKumar7 approved these changes

2022-10-17 02:13 UTC, merged